image:
  file: Dockerfile
ports:
  - port: 6080
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
  - port: 35900
    onOpen: ignore
checkoutLocation: "/tmp/eclipse-installer"
workspaceLocation: "."
tasks:
  - command: ./eclipse-inst